---
# IMPORTANT: Change settings here, but DO NOT change the spacing.
# Remove comments and add values where applicable.
# The descriptions below should be self-explanatory

title: "Helping You Write Academic Papers in R using Texevier"
#subtitle: "This will appear as Right Header"

documentclass: "elsarticle"

# --------- Thesis title (Optional - set to FALSE by default).
# You can move the details below around as you please.
Thesis_FP: FALSE
# Entry1: "An unbelievable study with a title spanning multiple lines."
# Entry2: "\\textbf{Some Guy}" # textbf for bold
# Entry3: "A thesis submitted toward the degree of Doctor of Philosophy"
# Uni_Logo: Tex/Logo.png # Place a logo in the indicated location (from your root, e.g. defaults to ~/Tex/Logo.png) and uncomment this line. Leave uncommented for no image
# Logo_width: 0.3 # If using a logo - use this to set width (size) of image
# Entry4: "Under the supervision of: \\vfill Prof. Joe Smith and Dr. Frank Smith"
# Entry5: "Stellenbosch University"
# Entry6: April 2020
# Entry7:
# Entry8:

# --------- Front Page
# Comment: ----- Follow this pattern for up to 5 authors
AddTitle: TRUE # Use FALSE when submitting to peer reviewed platform. This will remove author names.
Author1: "Jane Doe^[__Contributions:__  \\newline _The authors would like to thank no institution for money donated to this project. Thank you sincerely._]"  # First Author - note the thanks message displayed as an italic footnote of first page.
Ref1: "Some Institution, Cape Town, South Africa" # First Author's Affiliation
Email1: "nfkatzke\\@gmail.com" # First Author's Email address

Author2: "John Smith"
Ref2: "Some other Institution, Cape Town, South Africa"
Email2: "John\\@gmail.com"
CommonAffiliation_12: TRUE # If Author 1 and 2 have a common affiliation. Works with _13, _23, etc.

Author3: "John Doe"
Email3: "Joe\\@gmail.com"

CorrespAuthor_1: TRUE  # If corresponding author is author 3, e.g., use CorrespAuthor_3: TRUE

# Comment out below to remove both. JEL Codes only given if keywords also given.
keywords: "Multivariate GARCH \\sep Kalman Filter \\sep Copula" # Use \\sep to separate
JELCodes: "L250 \\sep L100"

# ----- Manage headers and footers:
#BottomLFooter: $Title$
#BottomCFooter:
#TopLHeader: \leftmark # Adds section name at topleft. Remove comment to add it.
BottomRFooter: "\\footnotesize Page \\thepage" # Add a '#' before this line to remove footer.
addtoprule: TRUE
addfootrule: TRUE               # Use if footers added. Add '#' to remove line.

# --------- page margins:
margin: 2.3 # Sides
bottom: 2 # bottom
top: 2.5 # Top
HardSet_layout: TRUE # Hard-set the spacing of words in your document. This will stop LaTeX squashing text to fit on pages, e.g.
# This is done by hard-setting the spacing dimensions. Set to FALSE if you want LaTeX to optimize this for your paper.

# --------- Line numbers
linenumbers: FALSE # Used when submitting to journal

# ---------- References settings:
# You can download cls format here: https://www.zotero.org/ - simply search for your institution. You can also edit and save cls formats here: https://editor.citationstyles.org/about/
# Hit download, store it in Tex/ folder, and change reference below - easy.
bibliography: Tex/ref.bib       # Do not edit: Keep this naming convention and location.
csl: Tex/harvard-stellenbosch-university.csl # referencing format used.
# By default, the bibliography only displays the cited references. If you want to change this, you can comment out one of the following:
#nocite: '@*' # Add all items in bibliography, whether cited or not
# nocite: |  # add specific references that aren't cited
#  @grinold2000
#  @Someoneelse2010

# ---------- General:
RemovePreprintSubmittedTo: TRUE  # Removes the 'preprint submitted to...' at bottom of titlepage
Journal: "Journal of Finance"   # Journal that the paper will be submitting to, if RemovePreprintSubmittedTo is set to TRUE.
toc: FALSE                       # Add a table of contents
numbersections: TRUE             # Should sections (and thus figures and tables) be numbered?
fontsize: 11pt                  # Set fontsize
linestretch: 1.2                # Set distance between lines.
link-citations: TRUE            # This creates dynamic links to the papers in reference list.

### Adding additional latex packages:
# header-includes:
#    - \usepackage{colortbl} # Add additional packages here.

output:
  pdf_document:
    keep_tex: TRUE
    template: Tex/TexDefault.txt
    fig_width: 3.5 # Adjust default figure sizes. This can also be done in the chunks of the text.
    fig_height: 3.5
abstract: |
  Abstract to be written here. The abstract should not be too long and should provide the reader with a good understanding what you are writing about. Academic papers are not like novels where you keep the reader in suspense. To be effective in getting others to read your paper, be as open and concise about your findings here as possible. Ideally, upon reading your abstract, the reader should feel he / she must read your paper in entirety.
---

<!-- First: Set your default preferences for chunk options: -->

<!-- If you want a chunk's code to be printed, set echo = TRUE. message = FALSE stops R printing ugly package loading details in your final paper too. I also suggest setting warning = FALSE and checking for warnings in R, else you might find ugly warnings in your paper. -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')

if(!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)
library(pacman)

source("code/perf_comparisons.R")



```


<!-- ############################## -->
<!-- # Start Writing here: -->
<!-- ############################## -->

```{r}
ALSI <- read_rds("data/ALSI.rds")
RebDays <- read_rds("data/Rebalance_days.rds")
ZAR <- read_rds("data/Monthly_zar.rds")
```


```{r Figure1,  warning =  FALSE, fig.align = 'center', fig.cap = "Caption Here \\label{Figure1}", fig.ext = 'png', fig.height = 3, fig.width = 6}
options(scipen = 999)
Year_Month <- function(x) format(as.Date(x), "%Y_%B")


monthlyALSI <- ALSI %>% 
    filter(year(date) >= 2014) %>% 
    mutate(YM = Year_Month(date)) %>% 
    mutate(monthlyIndex =cumprod(1 + Return)) %>% 
    group_by(YM) %>% 
    filter(date == last(date)) %>% 
    group_by(Tickers) %>% 
    mutate(MonthlyReturn = monthlyIndex/lag(monthlyIndex) - 1) %>% 
    filter(!is.na(MonthlyReturn))%>% 
    select(c(-monthlyIndex, -Return))
   

# WeightedAllShare <- monthlyALSI %>% 
#     mutate(contribution = J203 * MonthlyReturn) %>% 
#     group_by(date) %>% 
#     summarise(AllShareReturn = sum(contribution))
# WeightedAllShare


CapPerformance <- ALSI %>% 
    filter(year(date) >= 2014) %>%  #Small cap stocks have a lot of NA's pre 2014. so I remove this data
    group_by(date, Index_Name) %>%
    summarise(averageReturn = mean(Return, na.rm = TRUE))

monthlyReturns <- CapPerformance %>% 
    mutate(YM = Year_Month(date)) %>% 
    mutate(monthlyIndex =cumprod(1 + averageReturn)) %>% 
    group_by(YM) %>% 
    filter(date == last(date)) %>% 
    group_by(Index_Name) %>% 
    mutate(MonthlyReturn = monthlyIndex/lag(monthlyIndex) - 1) %>% 
    filter(!is.na(MonthlyReturn)) %>% 
    select(c(date,Index_Name,MonthlyReturn))

SWIX_new <- SWIX %>% 
    mutate(YM = Year_Month(date)) %>% 
    select(c(Returns, YM))
colnames(SWIX_new) <- c('SWIX', 'YM')


monthlyReturns_joined <- monthlyReturns %>% 
    pivot_wider(names_from = Index_Name,
                values_from = MonthlyReturn) %>% 
    mutate(YM = Year_Month(date)) %>% 
    left_join(SWIX_new, by = 'YM') %>% 
    select(-YM) %>% 
    pivot_longer(-date,
                 names_to = 'Type',
                 values_to = 'Returns') %>% 
    na.omit() %>% 
    filter(Type != 'NA')


cap_plot <- ggplot(monthlyReturns_joined, aes(x = Returns, fill = Type)) +
    geom_density(alpha = 0.5) +
    geom_vline(xintercept = 0, linetype = "dashed", color = "black")+
    labs(title = "Density of Returns by Type vs SWIX",
       x = "Returns",
       y = "Density") +
    theme_minimal()+
    theme(panel.border = element_rect(colour = "black", fill=NA, size=1),
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.box.background = element_rect(color = "black"))

cap_plot

top_40_average_J203 <- ALSI %>%
  group_by(Tickers) %>%
  summarise(average_J203 = mean(J203, na.rm = TRUE)) %>%
  arrange(desc(average_J203)) %>%
  slice_head(n = 40)

TopTickers <- unique(top_40_average_J203$Tickers)


SectorPerformance <- ALSI %>% 
    filter(Tickers %in% TopTickers) %>% 
    filter(year(date) >= 2014) %>%  #Small cap stocks have a lot of NA's pre 2014. so I remove this data
    group_by(date, Sector) %>%
    summarise(averageReturn = mean(Return, na.rm = TRUE))

monthlyReturns_sect <- SectorPerformance %>% 
    mutate(YM = Year_Month(date)) %>% 
    mutate(monthlyIndex =cumprod(1 + averageReturn)) %>% 
    group_by(YM) %>% 
    filter(date == last(date)) %>% 
    group_by(Sector) %>% 
    mutate(MonthlyReturn = monthlyIndex/lag(monthlyIndex) - 1) %>% 
    filter(!is.na(MonthlyReturn)) %>% 
    select(c(date,Sector,MonthlyReturn))

monthlyReturns_sect_joined <- monthlyReturns_sect %>% 
    pivot_wider(names_from = Sector,
                values_from = MonthlyReturn) %>% 
    mutate(YM = Year_Month(date)) %>% 
    left_join(SWIX_new, by = 'YM') %>% 
    select(-YM) %>% 
    pivot_longer(-date,
                 names_to = 'Sector',
                 values_to = 'Returns') %>% 
    na.omit() %>% 
    filter(Sector != 'NA')


sect_plot <- ggplot(monthlyReturns_sect_joined, aes(x = Returns, fill = Sector)) +
    geom_density(alpha = 0.5) +
    geom_vline(xintercept = 0, linetype = "dashed", color = "black")+
    labs(title = "Density of Returns by Sector vs SWIX",
       x = "Returns",
       y = "Density") +
    theme_minimal()+
    theme(panel.border = element_rect(colour = "black", fill=NA, size=1),
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.box.background = element_rect(color = "black"))

sect_plot


```





```{r}
library(rmsfuns)
library(kableExtra)
pacman::p_load("tidyr", "tbl2xts","devtools","lubridate", "readr", "PerformanceAnalytics", "ggplot2", "dplyr")



yearlyReturns_sect <- SectorPerformance %>% 
    mutate(Year = format(date, '%Y')) %>% 
    mutate(yearlyIndex =cumprod(1 + averageReturn)) %>% 
    group_by(Year) %>% 
    filter(date == last(date)) %>% 
    group_by(Sector) %>% 
    mutate(yearlyReturn = yearlyIndex/lag(yearlyIndex) - 1) %>% 
    filter(!is.na(yearlyReturn)) %>% 
    select(c(date,Sector,yearlyReturn))

#Winzorising
yearlyReturns_sect_df <- yearlyReturns_sect %>% 
    mutate(Year = format(date, "%Y")) %>% 
    group_by(Sector) %>% 
    mutate(Top = quantile(yearlyReturn, 0.99), Bot = quantile(yearlyReturn, 0.01)) %>% 
    mutate(Return = ifelse(yearlyReturn > Top, 
                           Top, 
                           ifelse(yearlyReturn < Bot, Bot, yearlyReturn))) %>% 
    ungroup()


ZAR_returns <- ZAR %>% 
    mutate(Return = value/lag(value)-1) %>% 
    filter(date > first(date)) %>% 
    select(c(date, Return))


ZAR_sd <- ZAR_returns %>% 
    mutate(Year = format(date, '%Y')) %>% 
    group_by(Year) %>% 
    summarise(SD = sd(Return)*sqrt(12)) %>% 
  
    mutate(TopQuantile = quantile(SD, 0.8), BotQuantile = quantile(SD, 0.2))

Hi_Vol <- ZAR_sd %>%  filter(SD > TopQuantile) %>% pull(Year)
Low_Vol <- ZAR_sd %>%  filter(SD < BotQuantile) %>% pull(Year)



perf_hi <- Perf_comparisons(yearlyReturns_sect_df, YMs = Hi_Vol, Alias = "High_Vol")
perf_lo <- Perf_comparisons(yearlyReturns_sect_df, YMs = Low_Vol, Alias = "Low_Vol")

RatioTable <- kable(perf_hi)
RatioTable

```


## Second Attempt

```{r}
ALSI <- read_rds("data/ALSI.rds")
RebDays <- read_rds("data/Rebalance_days.rds")
ZAR <- read_rds("data/Monthly_zar.rds")


```


```{r}
# Create portfolio return function

# Sector and Index as input
# Portfolio returns for both SWIX and ALSI as output

pacman::p_load(tbl2xts, PerformanceAnalytics)

port_ret_func <- function(data = ALSI, sector = "", index = ""){
    fund <- data
    
    if(!sector == ""){
        fund <- data %>% filter(Sector %in% sector) %>% 
            group_by(date) %>% 
            mutate(J403 = J403/sum(J403, na.rm = TRUE), J203 = J203/sum(J203, na.rm = TRUE)) %>% 
            ungroup()
    } 
    if(!index == ""){
        fund <- data %>% filter(Index_Name %in% index) %>% 
            group_by(date) %>% 
            mutate(J403 = J403/sum(J403, na.rm = TRUE), J203 = J203/sum(J203, na.rm = TRUE)) %>% 
            ungroup()
    } 
    if(!sector == "" & !index == ""){
        fund <- data %>%
            group_by(date) %>% 
            mutate(J403 = J403/sum(J403, na.rm = TRUE), J203 = J203/sum(J203, na.rm = TRUE)) %>% 
            ungroup()
    }
    
    fund_J203_weights <- fund %>% select(date, Tickers, J203) %>% mutate(J203 = coalesce(J203, 0)) %>%
        spread(Tickers, J203) %>% 
        tbl_xts()
    fund_J203_weights[is.na(fund_J203_weights)] <- 0
    
    fund_J403_weights <- fund %>% select(date, Tickers, J403) %>% spread(Tickers, J403) %>% tbl_xts()
    fund_J403_weights[is.na(fund_J403_weights)] <- 0
    
    fund_returns <- fund %>% select(date, Tickers, Return) %>% spread(Tickers, Return)
    fund_returns[is.na(fund_returns)] <- 0
    fund_returns_xts <- fund_returns %>% tbl_xts()
    
    J203_RetPort <- rmsfuns::Safe_Return.portfolio(fund_returns_xts,
    weights = fund_J203_weights, lag_weights = TRUE,
    contribution = TRUE, verbose = TRUE,
    value = 1, geometric = TRUE)
    
    J403_RetPort <- rmsfuns::Safe_Return.portfolio(R = fund_returns_xts,
    weights = fund_J403_weights, lag_weights = TRUE,
    contribution = TRUE, verbose = TRUE,
    value = 1000, geometric = TRUE)
    
    # Clean and save portfolio returns and weights:
    J203_Contribution <- J203_RetPort$"contribution" %>% xts_tbl() %>%
        mutate(date = lag(date), date = coalesce(date, index(fund_J203_weights)[1]) )

    J203_BPWeight <- J203_RetPort$"BOP.Weight" %>% xts_tbl() %>%
        mutate(date = lag(date), date = coalesce(date, index(fund_J203_weights)[1]) )
    
    J203_BPValue <- J203_RetPort$"BOP.Value" %>% xts_tbl() %>% 
        mutate(date = lag(date), date = coalesce(date, index(fund_J203_weights)[1]) )
    
        # Clean and save portfolio returns and weights:
    J403_Contribution <- J403_RetPort$"contribution" %>% xts_tbl() %>%
        mutate(date = lag(date), date = coalesce(date, index(fund_J403_weights)[1]) )
    
    J403_BPWeight <- J403_RetPort$"BOP.Weight" %>% xts_tbl() %>%
        mutate(date = lag(date), date = coalesce(date, index(fund_J403_weights)[1]) )
    
    J403_BPValue <- J403_RetPort$"BOP.Value" %>% xts_tbl() %>% 
        mutate(date = lag(date), date = coalesce(date, index(fund_J403_weights)[1]) )


names(J203_Contribution) <- c("date", names(J203_RetPort$"contribution"))
names(J203_BPWeight) <- c("date", names(J203_RetPort$"BOP.Weight"))
names(J203_BPValue) <- c("date", names(J203_RetPort$"BOP.Value"))
names(J403_Contribution) <- c("date", names(J403_RetPort$"contribution"))
names(J403_BPWeight) <- c("date", names(J403_RetPort$"BOP.Weight"))
names(J403_BPValue) <- c("date", names(J403_RetPort$"BOP.Value"))

# Let's bind all of these together now:
df_port_return_J203 <-
left_join(fund %>% select(date, Tickers, Return),
J203_BPWeight %>% gather(Tickers, weight, -date),
by = c("date", "Tickers") ) %>%
left_join(.,
J203_BPValue %>% gather(Tickers, value_held, -date),
by = c("date", "Tickers") ) %>%
left_join(.,
J203_Contribution %>% gather(Tickers, Contribution, -date),
by = c("date", "Tickers"))

df_port_return_J403 <-
left_join(fund %>% select(date, Tickers, Return),
J403_BPWeight %>% gather(Tickers, weight, -date),
by = c("date", "Tickers") ) %>%
left_join(.,
J403_BPValue %>% gather(Tickers, value_held, -date),
by = c("date", "Tickers") ) %>%
left_join(.,
J403_Contribution %>% gather(Tickers, Contribution, -date),
by = c("date", "Tickers"))

# Calculate Portfolio Returns:
df_Portf_J203<- df_port_return_J203 %>% group_by(date) %>% summarise(PortfolioReturn = sum(Return*weight, na.rm = TRUE)) %>% 
filter(PortfolioReturn != 0)
# Calculate Portfolio Returns:
df_Portf_J403 <-
df_port_return_J403 %>% group_by(date) %>% summarise(PortfolioReturn = sum(Return*weight, na.rm = TRUE)) %>% filter(PortfolioReturn != 0)
    
out <- left_join(df_Portf_J203 %>% rename(J203 = PortfolioReturn), 
                 df_Portf_J403 %>%  rename(J403 = PortfolioReturn), by = "date") %>% 
    pivot_longer(c("J203", "J403"), names_to = "Meth", values_to = "Returns")
out
}
```

```{r}
library(fmxdat)
# Compare Sectors for ALSI and SWIX

sectors <- ALSI %>% pull(Sector) %>% unique()
sector_ret <- list()

for(i in 1:length(sectors)){
    # Loop through sectors and calculate returns and cumulative returns
    sector_ret[[i]] <- port_ret_func(ALSI, sector = sectors[i]) %>% group_by(Meth) %>% 
    mutate(cumreturn_Rand = (cumprod(1 + 
    Returns))) %>% # Start at 1
mutate(cumreturn_Rand = cumreturn_Rand/first(cumreturn_Rand)) %>% 
    mutate(Sector = sectors[i])
}
# Rename tibbles
names(sector_ret) <- sectors
# Combine Dataframes

sectors_cum_ret <- rbind(sector_ret[[1]],
                             sector_ret[[2]], 
                             sector_ret[[3]]) %>% arrange(date)
    
q2_p1 <- sectors_cum_ret %>% 
        ggplot() +
        geom_line(aes(date, cumreturn_Rand, colour = Meth), alpha = 0.8) + facet_wrap(~Sector) + fmxdat::fmx_cols() + 
        labs(title = "Cumulative Returns per Sector for ALSI and SWIX", y = "Cumulative Returns", x = "") +
        fmxdat::theme_fmx(title.size = ggpts(25))

finplot(q2_p1)
```
```{r}
# Compare indeices for ALSI and SWIX

indices <- ALSI %>%  pull(Index_Name) %>% na.omit(.) %>%  unique()
indices_ret <- list()

for(i in 1:length(indices)){
    # Loop through sectors and calculate returns and cumulative returns
    indices_ret[[i]] <- port_ret_func(ALSI,index = indices[i]) %>% group_by(Meth) %>% 
    mutate(cumreturn_Rand = (cumprod(1 + 
    Returns))) %>% # Start at 1
mutate(cumreturn_Rand = cumreturn_Rand/first(cumreturn_Rand)) %>% 
    mutate(Index = indices[i])
}
# Rename tibbles
names(indices_ret) <- indices
# Combine Dataframes

indices_cum_ret <- rbind(indices_ret[[1]],
                             indices_ret[[2]], 
                             indices_ret[[3]]) %>% arrange(date)
    
q2_p2 <- indices_cum_ret %>% 
        ggplot() +
        geom_line(aes(date, cumreturn_Rand, colour = Meth), alpha = 0.8) + facet_wrap(~Index) + fmxdat::fmx_cols() + 
        labs(title = "Cumulative Returns per Index for ALSI and SWIX", y = "Cumulative Returns", x = "") +
        fmxdat::theme_fmx(title.size = ggpts(25))

finplot(q2_p2)
```
```{r}
# Construct Capped Portfolio and Determine Performance for ALSI

reb_ALSI <- ALSI %>% 
filter(date %in% RebDays$date) %>% 
# Now we have to distinguish rebalances - to create something
# to group by:
mutate(RebalanceTime = format(date, "%Y%B")) %>% 
    select(date, Tickers, Return, J203, RebalanceTime) %>% 
    rename(weight = J203) %>% 
    mutate(weight = coalesce(weight , 0))

## Uncomment for stepping through function:
# df_Cons <- rebalance_col %>% filter(date == first(date))
# W_Cap = 0.08

Proportional_Cap_Foo <- function(df_Cons, W_Cap = 0.08){
  
  # Let's require a specific form from the user... Alerting when it does not adhere this form
  if( !"weight" %in% names(df_Cons)) stop("... for Calc capping to work, provide weight column called 'weight'")
  
  if( !"date" %in% names(df_Cons)) stop("... for Calc capping to work, provide date column called 'date'")
  
  if( !"Tickers" %in% names(df_Cons)) stop("... for Calc capping to work, provide id column called 'Tickers'")

  # First identify the cap breachers...
  Breachers <- 
    df_Cons %>% filter(weight > W_Cap) %>% pull(Tickers)
  
  # Now keep track of breachers, and add to it to ensure they remain at 10%:
  if(length(Breachers) > 0) {
    
    while( df_Cons %>% filter(weight > W_Cap) %>% nrow() > 0 ) {
      
      
      df_Cons <-
        
        bind_rows(
          
          df_Cons %>% filter(Tickers %in% Breachers) %>% mutate(weight = W_Cap),
          
          df_Cons %>% filter(!Tickers %in% Breachers) %>% 
            mutate(weight = (weight / sum(weight, na.rm=T)) * (1-length(Breachers)*W_Cap) )
          
        )
      
      Breachers <- c(Breachers, df_Cons %>% filter(weight > W_Cap) %>% pull(Tickers))
      
    }

    if( sum(df_Cons$weight, na.rm=T) > 1.1 | sum(df_Cons$weight, na.rm=T) < 0.9 | max(df_Cons$weight, na.rm = T) > W_Cap) {
      
      stop( glue::glue("For the Generic weight trimming function used: the weight trimming causes non unit 
      summation of weights for date: {unique(df_Cons$date)}...\n
      The restriction could be too low or some dates have extreme concentrations...") )
      
    }
    
  } else {
    
  }
  
  df_Cons
  
  }
  
# Apply Proportional_Cap_Foo to ALSI to get capped return for cap of 10%
Capped_df <- 
reb_ALSI %>% 
group_split(RebalanceTime) %>% 
map_df(~Proportional_Cap_Foo(., W_Cap = 0.1) ) %>% select(-RebalanceTime)
 
ALSI_wts <- Capped_df %>% tbl_xts(cols_to_xts = weight, spread_by = Tickers)

ALSI_rts <- ALSI %>% 
filter(Tickers %in% unique(Capped_df$Tickers)) %>% 
tbl_xts(cols_to_xts = Return, spread_by = Tickers)

ALSI_wts[is.na(ALSI_wts)] <- 0

ALSI_rts[is.na(ALSI_rts)] <- 0

ALSI_capped <- rmsfuns::Safe_Return.portfolio(R = ALSI_rts, weights = ALSI_wts, 
    lag_weights = T) %>% 
xts_tbl() %>% 
rename(ALSI = portfolio.returns)

# Construct Capped Portfolio and Determine Performance for SWIX

reb_SWIX <- ALSI %>% 
filter(date %in% RebDays$date) %>% 
mutate(RebalanceTime = format(date, "%Y%B")) %>% 
    select(date, Tickers, Return, J403, RebalanceTime) %>% 
    rename(weight = J403) %>% 
    mutate(weight = coalesce(weight , 0))
  
# Apply Proportional_Cap_Foo to ALSI to get capped return for cap of 6%
Capped_df <- 
reb_SWIX %>% 
group_split(RebalanceTime) %>% 
map_df(~Proportional_Cap_Foo(., W_Cap = 0.06) ) %>% select(-RebalanceTime)
 
SWIX_wts <- Capped_df %>% tbl_xts(cols_to_xts = weight, spread_by = Tickers)

SWIX_rts <- ALSI %>% 
filter(Tickers %in% unique(Capped_df$Tickers)) %>% 
tbl_xts(cols_to_xts = Return, spread_by = Tickers)

SWIX_wts[is.na(SWIX_wts)] <- 0

SWIX_rts[is.na(SWIX_rts)] <- 0

SWIX_capped <- rmsfuns::Safe_Return.portfolio(R = SWIX_rts, weights = SWIX_wts, 
    lag_weights = T) %>% 
xts_tbl() %>% 
rename(SWIX = portfolio.returns)


# Combine and Plot Performance

capped_indices <- left_join(ALSI_capped, SWIX_capped, by = "date") %>% 
    pivot_longer(c("ALSI", "SWIX"), names_to = "Meth", values_to = "returns")

# Calculate Uncapped Return for ALSI
ALSI_wts <- ALSI %>% 
filter(date %in% RebDays$date) %>% 
mutate(RebalanceTime = format(date, "%Y%B")) %>% 
    rename(weight = J203) %>% 
    mutate(weight = coalesce(weight , 0)) %>% 
    select(date, Tickers, Return, weight, RebalanceTime) %>% 
     tbl_xts(cols_to_xts = weight, spread_by = Tickers)

ALSI_wts[is.na(ALSI_wts)] <- 0

ALSI_rts[is.na(ALSI_rts)] <- 0

ALSI_capped <- rmsfuns::Safe_Return.portfolio(R = ALSI_rts, weights = ALSI_wts, 
    lag_weights = T) %>% 
xts_tbl() %>% 
rename(ALSI = portfolio.returns)

# Calculate Uncapped Return for SWIX
 
SWIX_wts <- ALSI %>% 
filter(date %in% RebDays$date) %>% 
mutate(RebalanceTime = format(date, "%Y%B")) %>% 
    rename(weight = J403) %>% 
    mutate(weight = coalesce(weight , 0)) %>% 
    select(date, Tickers, Return, weight, RebalanceTime) %>% 
     tbl_xts(cols_to_xts = weight, spread_by = Tickers)

SWIX_wts[is.na(SWIX_wts)] <- 0

SWIX_rts[is.na(SWIX_rts)] <- 0

SWIX_capped <- rmsfuns::Safe_Return.portfolio(R = SWIX_rts, weights = SWIX_wts, 
    lag_weights = T) %>% 
xts_tbl() %>% 
rename(SWIX = portfolio.returns)

# Combine and Plot

ALSI_SWIX <- left_join(ALSI_capped, SWIX_capped, by = "date") %>% 
    pivot_longer(c("ALSI", "SWIX"), names_to = "Meth", values_to = "Returns")

q2_p3 <- capped_indices %>% 
    group_by(Meth) %>%
    mutate(Idx = cumprod(1 + returns)) %>% 
ggplot() + 
geom_line(aes(date, Idx, colour = Meth), alpha = 0.8) + 
labs(subtitle = "ALSI capped at 10% and SWIX at 6%", 
    x = "", y = "Cumulative Return") + 
    fmx_cols() + 
fmxdat::theme_fmx(subtitle.size = ggpts(20))

q2_p4 <- ALSI_SWIX %>% 
    group_by(Meth) %>%
    mutate(Idx = cumprod(1 + Returns)) %>% 
ggplot() + 
geom_line(aes(date, Idx, colour = Meth), alpha = 0.8) + 
labs(subtitle = "Uncapped Index Calculation for ALSI and SWIX", 
    x = "", y = "Cumulative Return") + 
    fmx_cols() + 
fmxdat::theme_fmx(subtitle.size = ggpts(20))

plot_grid(finplot(q2_p3), finplot(q2_p4), labels = list(title = "Comparing Capped and Uncapped returns of ALSI and SWIX"), label_size = ggpts(30), align = "h")
```

